[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scikit-covtest"
version = "0.0.1"
description = "Covariance Hypothesis Testing and Evaluation"
authors = [
    { name = "Austin Talbot", email = "austin.talbot1993@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "scipy",
    "tqdm",
    "cloudpickle",
    "matplotlib",
    "cvxpy",
    "statsmodels",
]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
docs = ["Sphinx", "sphinx-rtd-theme", "docutils"]

[project.urls]
Homepage = "https://github.com/bystrogenomics/scikit-covtest"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["covtest*"]

[tool.setuptools.package-data]
"covtest.datasets" = ["data/*.npz"]
"covtest.methods" = ["*.p"]

[tool.ruff]
line-length = 80
ignore = ["E501"]

[tool.black]
line-length = 80
