[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scikit-covtest"
version = "0.1.0"
description = "Covariance Hypothesis Testing and Evaluation"
authors = [
    { name = "Austin Talbot", email = "austin.talbot1993@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"

dependencies = [
    "numba",
    "numpy",
    "pandas",
    "scikit-learn",
    "scipy",
    "tqdm",
    "cloudpickle",
    "matplotlib",
    "cvxpy",
    "statsmodels",
    "pytest",
]

[project.urls]
Homepage = "https://github.com/bystrogenomics/scikit-covtest"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["covtest*"]

[tool.setuptools.package-data]
"covtest.datasets" = ["data/*.npz"]

[tool.ruff]
line-length = 80

[tool.ruff.lint]
ignore = ["E501"]

[tool.black]
line-length = 80
