[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scikit-covtest"
version = "0.1.0"
description = "Covariance Hypothesis Testing and Evaluation"
authors = [
    { name="Austin Talbot", email="austin.talbot1993@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
dependencies = [
        'numba',
        'numpy',
        'pandas',
        'scikit-learn',
        'scipy',
        'tqdm',
        'cloudpickle',
        'matplotlib',
        'cvxpy',
        'statsmodels',
        'pytest',
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/bystrogenomics/scikit-covtest"

